// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: datasource/service.proto

package datasource

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on AnalyzeAttackFlowRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AnalyzeAttackFlowRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AnalyzeAttackFlowRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AnalyzeAttackFlowRequestMultiError, or nil if none found.
func (m *AnalyzeAttackFlowRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *AnalyzeAttackFlowRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetProjectId() <= 0 {
		err := AnalyzeAttackFlowRequestValidationError{
			field:  "ProjectId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetResourceName()); l < 1 || l > 255 {
		err := AnalyzeAttackFlowRequestValidationError{
			field:  "ResourceName",
			reason: "value length must be between 1 and 255 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := _AnalyzeAttackFlowRequest_CloudType_InLookup[m.GetCloudType()]; !ok {
		err := AnalyzeAttackFlowRequestValidationError{
			field:  "CloudType",
			reason: "value must be in list [aws]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetCloudId()); l < 1 || l > 32 {
		err := AnalyzeAttackFlowRequestValidationError{
			field:  "CloudId",
			reason: "value length must be between 1 and 32 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return AnalyzeAttackFlowRequestMultiError(errors)
	}

	return nil
}

// AnalyzeAttackFlowRequestMultiError is an error wrapping multiple validation
// errors returned by AnalyzeAttackFlowRequest.ValidateAll() if the designated
// constraints aren't met.
type AnalyzeAttackFlowRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AnalyzeAttackFlowRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AnalyzeAttackFlowRequestMultiError) AllErrors() []error { return m }

// AnalyzeAttackFlowRequestValidationError is the validation error returned by
// AnalyzeAttackFlowRequest.Validate if the designated constraints aren't met.
type AnalyzeAttackFlowRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AnalyzeAttackFlowRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AnalyzeAttackFlowRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AnalyzeAttackFlowRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AnalyzeAttackFlowRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AnalyzeAttackFlowRequestValidationError) ErrorName() string {
	return "AnalyzeAttackFlowRequestValidationError"
}

// Error satisfies the builtin error interface
func (e AnalyzeAttackFlowRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAnalyzeAttackFlowRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AnalyzeAttackFlowRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AnalyzeAttackFlowRequestValidationError{}

var _AnalyzeAttackFlowRequest_CloudType_InLookup = map[string]struct{}{
	"aws": {},
}

// Validate checks the field values on AnalyzeAttackFlowResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AnalyzeAttackFlowResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AnalyzeAttackFlowResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AnalyzeAttackFlowResponseMultiError, or nil if none found.
func (m *AnalyzeAttackFlowResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *AnalyzeAttackFlowResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetNodes() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, AnalyzeAttackFlowResponseValidationError{
						field:  fmt.Sprintf("Nodes[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, AnalyzeAttackFlowResponseValidationError{
						field:  fmt.Sprintf("Nodes[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return AnalyzeAttackFlowResponseValidationError{
					field:  fmt.Sprintf("Nodes[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	for idx, item := range m.GetEdges() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, AnalyzeAttackFlowResponseValidationError{
						field:  fmt.Sprintf("Edges[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, AnalyzeAttackFlowResponseValidationError{
						field:  fmt.Sprintf("Edges[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return AnalyzeAttackFlowResponseValidationError{
					field:  fmt.Sprintf("Edges[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return AnalyzeAttackFlowResponseMultiError(errors)
	}

	return nil
}

// AnalyzeAttackFlowResponseMultiError is an error wrapping multiple validation
// errors returned by AnalyzeAttackFlowResponse.ValidateAll() if the
// designated constraints aren't met.
type AnalyzeAttackFlowResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AnalyzeAttackFlowResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AnalyzeAttackFlowResponseMultiError) AllErrors() []error { return m }

// AnalyzeAttackFlowResponseValidationError is the validation error returned by
// AnalyzeAttackFlowResponse.Validate if the designated constraints aren't met.
type AnalyzeAttackFlowResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AnalyzeAttackFlowResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AnalyzeAttackFlowResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AnalyzeAttackFlowResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AnalyzeAttackFlowResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AnalyzeAttackFlowResponseValidationError) ErrorName() string {
	return "AnalyzeAttackFlowResponseValidationError"
}

// Error satisfies the builtin error interface
func (e AnalyzeAttackFlowResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAnalyzeAttackFlowResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AnalyzeAttackFlowResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AnalyzeAttackFlowResponseValidationError{}
